/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppMembrosRouteImport } from './routes/_app.membros'
import { Route as AppEventosRouteImport } from './routes/_app.eventos'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppMembrosNovoRouteImport } from './routes/_app.membros.novo'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMembrosRoute = AppMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => AppRoute,
} as any)
const AppEventosRoute = AppEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppMembrosNovoRoute = AppMembrosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => AppMembrosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/eventos': typeof AppEventosRoute
  '/membros': typeof AppMembrosRouteWithChildren
  '/membros/novo': typeof AppMembrosNovoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AppDashboardRoute
  '/eventos': typeof AppEventosRoute
  '/membros': typeof AppMembrosRouteWithChildren
  '/membros/novo': typeof AppMembrosNovoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/eventos': typeof AppEventosRoute
  '/_app/membros': typeof AppMembrosRouteWithChildren
  '/_app/membros/novo': typeof AppMembrosNovoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard' | '/eventos' | '/membros' | '/membros/novo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard' | '/eventos' | '/membros' | '/membros/novo'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/dashboard'
    | '/_app/eventos'
    | '/_app/membros'
    | '/_app/membros/novo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/membros': {
      id: '/_app/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof AppMembrosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/eventos': {
      id: '/_app/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof AppEventosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/membros/novo': {
      id: '/_app/membros/novo'
      path: '/novo'
      fullPath: '/membros/novo'
      preLoaderRoute: typeof AppMembrosNovoRouteImport
      parentRoute: typeof AppMembrosRoute
    }
  }
}

interface AppMembrosRouteChildren {
  AppMembrosNovoRoute: typeof AppMembrosNovoRoute
}

const AppMembrosRouteChildren: AppMembrosRouteChildren = {
  AppMembrosNovoRoute: AppMembrosNovoRoute,
}

const AppMembrosRouteWithChildren = AppMembrosRoute._addFileChildren(
  AppMembrosRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppEventosRoute: typeof AppEventosRoute
  AppMembrosRoute: typeof AppMembrosRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppEventosRoute: AppEventosRoute,
  AppMembrosRoute: AppMembrosRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
